security:
    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: home
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false

        default:
            anonymous: ~
