security:
    providers:
        main:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
                default_target_path:            /liste_bd
            logout:
                path:   logout
                target: home
                
#        dev:
#            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
#            security: false

        default:
            anonymous: ~

    encoders:
            AppBundle\Entity\User:
                algorithm: sha512
                iterations: 5000

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/a_propos, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
