<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * serieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class serieRepository extends EntityRepository
{
}
